# Generated by Django 2.2.7 on 2019-12-04 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retirees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retired',
            old_name='modifieled_data',
            new_name='modified_data',
        ),
        migrations.RemoveField(
            model_name='retired',
            name='disease',
        ),
        migrations.CreateModel(
            name='RetiredInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True)),
                ('retired', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='retirees.Retired')),
            ],
        ),
        migrations.CreateModel(
            name='RetiredAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=100)),
                ('retired', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retirees.Retired')),
            ],
        ),
    ]
