# Generated by Django 2.2.7 on 2019-12-21 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retirees', '0002_auto_20191204_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retiredaddress',
            old_name='adress',
            new_name='address',
        ),
    ]
