# Generated by Django 2.2.7 on 2019-12-21 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapydisease',
            old_name='discription',
            new_name='description',
        ),
    ]
