# Generated by Django 2.2.7 on 2019-12-04 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retirees', '0002_auto_20191204_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symptoms', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=50)),
                ('the_cause', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseRetired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.TextField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseases.Disease')),
                ('retired', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retirees.Retired')),
            ],
        ),
    ]
